# Generated by Django 5.0 on 2024-01-09 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0005_alter_attendance_attendance_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbackstudent',
            old_name='feedback_replay',
            new_name='feedback_reply',
        ),
    ]
