# Generated by Django 5.0 on 2024-01-09 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0006_rename_feedback_replay_feedbackstudent_feedback_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavereport',
            name='leave_status',
            field=models.IntegerField(default=0),
        ),
    ]
